project:
  type: website

website:
  title: "My Math Blog"
  description: "Daily math notes and references"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: posts/

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    math-method: mathjax
    relative-links: true   # <-- THIS is the key
    css: styles/math.css
    site-navbar-search: true

bibliography: refs/references.bib
csl: refs/ams.csl

execute:
  echo: true
  warning: false
  error: false