project:
  type: website

website:
  title: "My Math Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: posts/

# <--- ADD THIS
site-url: "https://williamclarktennis.github.io/my-quarto-math-blog/"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    linestretch: 1.2
    include-in-header: preamble.tex
    css: styles/math.css
    html-math-method: mathjax

bibliography: refs/references.bib
csl: refs/ams.csl